/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import islandScene from "../assets/3d/island.glb";
import { a } from "@react-spring/three";

const Island = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const islandRef = useRef();

  const { gl } = useThree();
  const { nodes, materials } = useGLTF(islandScene);

  // 🔥 Smooth rotation physics
  const lastX = useRef(null);
  const velocity = useRef(0);
  const dragging = useRef(false);

  const FRICTION = 0.92;
  const SPEED = 0.003; // smooth, mobile-safe rotation speed

  /** ⛳ POINTER DOWN — Start dragging */
  const handlePointerDown = (e) => {
    e.stopPropagation();
    dragging.current = true;
    setIsRotating(true);

    const clientX =
      e.touches && e.touches.length ? e.touches[0].clientX : e.clientX;

    lastX.current = clientX;
  };

  /** 🎯 POINTER MOVE — Drag rotation */
  const handlePointerMove = (e) => {
    if (!dragging.current) return;

    const clientX =
      e.touches && e.touches.length ? e.touches[0].clientX : e.clientX;

    const deltaX = clientX - lastX.current;
    lastX.current = clientX;

    // Smooth rotation speed
    velocity.current = deltaX * SPEED;
  };

  /** 🛑 POINTER UP — Let momentum continue */
  const handlePointerUp = () => {
    dragging.current = false;
    setIsRotating(false);
    lastX.current = null;
  };

  /** ⏳ Smooth animation */
  useFrame(() => {
    // Apply velocity
    islandRef.current.rotation.y += velocity.current;

    // Apply friction when not dragging
    if (!dragging.current) {
      velocity.current *= FRICTION;

      if (Math.abs(velocity.current) < 0.0001) {
        velocity.current = 0;
      }
    }

    // Normalize rotation between 0 - 2π
    const rotation = islandRef.current.rotation.y;
    const normalizedRotation =
      ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    // Update stage based on angle
    switch (true) {
      case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
        setCurrentStage(4);
        break;
      case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
        setCurrentStage(3);
        break;
      case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
        setCurrentStage(2);
        break;
      case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
        setCurrentStage(1);
        break;
      default:
        setCurrentStage(null);
    }
  });

  /** 🎮 Attach Touch + Mouse events */
  useEffect(() => {
    const canvas = gl.domElement;

    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointermove", handlePointerMove);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointerleave", handlePointerUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointermove", handlePointerMove);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointerleave", handlePointerUp);
    };
  }, [gl]);

  return (
    <a.group ref={islandRef} {...props} dispose={null}>
      <mesh geometry={nodes.polySurface944_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface945_tree1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface946_tree2_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface947_tree1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface948_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface949_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.pCube11_rocks1_0.geometry} material={materials.PaletteMaterial001} />
    </a.group>
  );
};

useGLTF.preload("/island.glb");

export default Island;
